/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ShoeAuthenticity } from "./ShoeAuthenticity";
export * as factories from "./factories";
export { ShoeAuthenticity__factory } from "./factories/ShoeAuthenticity__factory";
