/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ShoeAuthenticity {
  export type CompanyStruct = {
    wallet: AddressLike;
    companyName: string;
    approved: boolean;
  };

  export type CompanyStructOutput = [
    wallet: string,
    companyName: string,
    approved: boolean
  ] & { wallet: string; companyName: string; approved: boolean };

  export type ShoeStruct = {
    productCode: string;
    brand: string;
    model: string;
    releaseYear: BigNumberish;
    companyWallet: AddressLike;
    authentic: boolean;
  };

  export type ShoeStructOutput = [
    productCode: string,
    brand: string,
    model: string,
    releaseYear: bigint,
    companyWallet: string,
    authentic: boolean
  ] & {
    productCode: string;
    brand: string;
    model: string;
    releaseYear: bigint;
    companyWallet: string;
    authentic: boolean;
  };
}

export interface ShoeAuthenticityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addShoe"
      | "admin"
      | "companies"
      | "getAllCompanies"
      | "getAllShoes"
      | "getCompanyShoes"
      | "getFeeStats"
      | "getShoe"
      | "registerCompany"
      | "registrationFee"
      | "registrationFeesCollected"
      | "setCompanyApproval"
      | "setFees"
      | "totalTransactions"
      | "updateShoe"
      | "verificationFee"
      | "verificationFeesCollected"
      | "verifyShoe"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompanyRegistered"
      | "FeeCollected"
      | "FeesWithdrawn"
      | "ProductRegistered"
      | "ProductVerified"
      | "ShoeRegistered"
      | "ShoeUpdated"
      | "ShoeVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addShoe",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "companies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCompanies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllShoes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCompanyShoes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeStats",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getShoe", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerCompany",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registrationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registrationFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCompanyApproval",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateShoe",
    values: [string, string, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verificationFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "verifyShoe", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addShoe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "companies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllCompanies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllShoes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompanyShoes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getShoe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCompanyApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateShoe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verificationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyShoe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace CompanyRegisteredEvent {
  export type InputTuple = [companyWallet: AddressLike];
  export type OutputTuple = [companyWallet: string];
  export interface OutputObject {
    companyWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [
    payer: AddressLike,
    amount: BigNumberish,
    transactionType: string
  ];
  export type OutputTuple = [
    payer: string,
    amount: bigint,
    transactionType: string
  ];
  export interface OutputObject {
    payer: string;
    amount: bigint;
    transactionType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRegisteredEvent {
  export type InputTuple = [shoeCode: string, company: AddressLike];
  export type OutputTuple = [shoeCode: string, company: string];
  export interface OutputObject {
    shoeCode: string;
    company: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductVerifiedEvent {
  export type InputTuple = [shoeCode: string, verifier: AddressLike];
  export type OutputTuple = [shoeCode: string, verifier: string];
  export interface OutputObject {
    shoeCode: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShoeRegisteredEvent {
  export type InputTuple = [productCode: string, brand: string];
  export type OutputTuple = [productCode: string, brand: string];
  export interface OutputObject {
    productCode: string;
    brand: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShoeUpdatedEvent {
  export type InputTuple = [productCode: string];
  export type OutputTuple = [productCode: string];
  export interface OutputObject {
    productCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShoeVerifiedEvent {
  export type InputTuple = [productCode: string, authentic: boolean];
  export type OutputTuple = [productCode: string, authentic: boolean];
  export interface OutputObject {
    productCode: string;
    authentic: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShoeAuthenticity extends BaseContract {
  connect(runner?: ContractRunner | null): ShoeAuthenticity;
  waitForDeployment(): Promise<this>;

  interface: ShoeAuthenticityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addShoe: TypedContractMethod<
    [
      _productCode: string,
      _brand: string,
      _model: string,
      _releaseYear: BigNumberish
    ],
    [void],
    "payable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  companies: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean] & {
        wallet: string;
        companyName: string;
        approved: boolean;
      }
    ],
    "view"
  >;

  getAllCompanies: TypedContractMethod<
    [],
    [ShoeAuthenticity.CompanyStructOutput[]],
    "view"
  >;

  getAllShoes: TypedContractMethod<
    [],
    [ShoeAuthenticity.ShoeStructOutput[]],
    "view"
  >;

  getCompanyShoes: TypedContractMethod<
    [_companyWallet: AddressLike],
    [ShoeAuthenticity.ShoeStructOutput[]],
    "view"
  >;

  getFeeStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalFeesCollected: bigint;
        registrationTotal: bigint;
        verificationTotal: bigint;
        transactionCount: bigint;
      }
    ],
    "view"
  >;

  getShoe: TypedContractMethod<
    [_productCode: string],
    [ShoeAuthenticity.ShoeStructOutput],
    "view"
  >;

  registerCompany: TypedContractMethod<
    [_companyName: string],
    [void],
    "nonpayable"
  >;

  registrationFee: TypedContractMethod<[], [bigint], "view">;

  registrationFeesCollected: TypedContractMethod<[], [bigint], "view">;

  setCompanyApproval: TypedContractMethod<
    [_companyWallet: AddressLike, _approved: boolean],
    [void],
    "nonpayable"
  >;

  setFees: TypedContractMethod<
    [_registrationFee: BigNumberish, _verificationFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalTransactions: TypedContractMethod<[], [bigint], "view">;

  updateShoe: TypedContractMethod<
    [
      _productCode: string,
      _brand: string,
      _model: string,
      _releaseYear: BigNumberish,
      _authentic: boolean
    ],
    [void],
    "nonpayable"
  >;

  verificationFee: TypedContractMethod<[], [bigint], "view">;

  verificationFeesCollected: TypedContractMethod<[], [bigint], "view">;

  verifyShoe: TypedContractMethod<[_productCode: string], [boolean], "payable">;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addShoe"
  ): TypedContractMethod<
    [
      _productCode: string,
      _brand: string,
      _model: string,
      _releaseYear: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "companies"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean] & {
        wallet: string;
        companyName: string;
        approved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllCompanies"
  ): TypedContractMethod<[], [ShoeAuthenticity.CompanyStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAllShoes"
  ): TypedContractMethod<[], [ShoeAuthenticity.ShoeStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getCompanyShoes"
  ): TypedContractMethod<
    [_companyWallet: AddressLike],
    [ShoeAuthenticity.ShoeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeeStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalFeesCollected: bigint;
        registrationTotal: bigint;
        verificationTotal: bigint;
        transactionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShoe"
  ): TypedContractMethod<
    [_productCode: string],
    [ShoeAuthenticity.ShoeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerCompany"
  ): TypedContractMethod<[_companyName: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registrationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registrationFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setCompanyApproval"
  ): TypedContractMethod<
    [_companyWallet: AddressLike, _approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [_registrationFee: BigNumberish, _verificationFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalTransactions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateShoe"
  ): TypedContractMethod<
    [
      _productCode: string,
      _brand: string,
      _model: string,
      _releaseYear: BigNumberish,
      _authentic: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verificationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verificationFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyShoe"
  ): TypedContractMethod<[_productCode: string], [boolean], "payable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CompanyRegistered"
  ): TypedContractEvent<
    CompanyRegisteredEvent.InputTuple,
    CompanyRegisteredEvent.OutputTuple,
    CompanyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ProductRegistered"
  ): TypedContractEvent<
    ProductRegisteredEvent.InputTuple,
    ProductRegisteredEvent.OutputTuple,
    ProductRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProductVerified"
  ): TypedContractEvent<
    ProductVerifiedEvent.InputTuple,
    ProductVerifiedEvent.OutputTuple,
    ProductVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ShoeRegistered"
  ): TypedContractEvent<
    ShoeRegisteredEvent.InputTuple,
    ShoeRegisteredEvent.OutputTuple,
    ShoeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ShoeUpdated"
  ): TypedContractEvent<
    ShoeUpdatedEvent.InputTuple,
    ShoeUpdatedEvent.OutputTuple,
    ShoeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ShoeVerified"
  ): TypedContractEvent<
    ShoeVerifiedEvent.InputTuple,
    ShoeVerifiedEvent.OutputTuple,
    ShoeVerifiedEvent.OutputObject
  >;

  filters: {
    "CompanyRegistered(address)": TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;
    CompanyRegistered: TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;

    "FeeCollected(address,uint256,string)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "ProductRegistered(string,address)": TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
    ProductRegistered: TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;

    "ProductVerified(string,address)": TypedContractEvent<
      ProductVerifiedEvent.InputTuple,
      ProductVerifiedEvent.OutputTuple,
      ProductVerifiedEvent.OutputObject
    >;
    ProductVerified: TypedContractEvent<
      ProductVerifiedEvent.InputTuple,
      ProductVerifiedEvent.OutputTuple,
      ProductVerifiedEvent.OutputObject
    >;

    "ShoeRegistered(string,string)": TypedContractEvent<
      ShoeRegisteredEvent.InputTuple,
      ShoeRegisteredEvent.OutputTuple,
      ShoeRegisteredEvent.OutputObject
    >;
    ShoeRegistered: TypedContractEvent<
      ShoeRegisteredEvent.InputTuple,
      ShoeRegisteredEvent.OutputTuple,
      ShoeRegisteredEvent.OutputObject
    >;

    "ShoeUpdated(string)": TypedContractEvent<
      ShoeUpdatedEvent.InputTuple,
      ShoeUpdatedEvent.OutputTuple,
      ShoeUpdatedEvent.OutputObject
    >;
    ShoeUpdated: TypedContractEvent<
      ShoeUpdatedEvent.InputTuple,
      ShoeUpdatedEvent.OutputTuple,
      ShoeUpdatedEvent.OutputObject
    >;

    "ShoeVerified(string,bool)": TypedContractEvent<
      ShoeVerifiedEvent.InputTuple,
      ShoeVerifiedEvent.OutputTuple,
      ShoeVerifiedEvent.OutputObject
    >;
    ShoeVerified: TypedContractEvent<
      ShoeVerifiedEvent.InputTuple,
      ShoeVerifiedEvent.OutputTuple,
      ShoeVerifiedEvent.OutputObject
    >;
  };
}
